name: best_price
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  bloc: ^8.1.3
  connectivity_plus: null
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  logger: ^2.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
 
  assets:
    - assets/images/splash/
    - assets/images/onBoarding/
    - assets/icons/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600
       
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
